[package]
org = "choreo"
name = "mediation.xml_to_json"
version = "2.0.0"
distribution = "2201.3.1"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-request-flow", "choreo-apim-mediation-response-flow"]

[build-options]
observabilityIncluded = true
