[package]
org = "choreo"
name = "oauth_mediator"
version = "1.0.0"
export = ["oauth_mediator"]
distribution = "2201.5.5"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow"]

[build-options]
observabilityIncluded = true
