[package]
org = "choreo"
name = "mediation.log_message"
version = "2.0.1"
distribution = "2201.3.1"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-request-flow", "choreo-apim-mediation-response-flow", "choreo-apim-mediation-fault-flow"]

[build-options]
observabilityIncluded = true
