[package]
org = "choreo"
name = "mediation.remove_query_param"
version = "0.2.0"
distribution = "2201.2.1"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-request-flow"]

[build-options]
observabilityIncluded = true
